# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_myuser_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user-images'),
        ),
    ]
