# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
    ]
