# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0011_auto_20161003_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
