# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_auto_20161003_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default='/static/images/cmu.jpg', upload_to='user-images'),
        ),
    ]
