# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_auto_20161003_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user-images'),
        ),
    ]
