# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MAIN', to=settings.AUTH_USER_MODEL),
        ),
    ]
