# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0019_auto_20161021_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 21, 19, 3, 14, 809436), verbose_name='date published'),
        ),
    ]
